# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: {{ include "common.name" . }}-credentials
#   labels:
#     {{- include "common.labels" . | nindent 4 }}
#   annotations:
#     {{- include "common.annotations" . | nindent 4 }}
#     sealedsecrets.bitnami.com/namespace-wide: "true"
#   namespace: {{ .Release.Namespace }}
# spec:
# {{- if .Values.sealedSecret.encryptedData }}
#   encryptedData:
# {{ toYaml .Values.sealedSecret.encryptedData | indent 4 }}
# {{- end }}
#   template:
#     metadata:
#       name: {{ include "common.name" . }}-credentials
#       labels:
#         {{- include "common.labels" . | nindent 8 }}
#       namespace: {{ .Release.Namespace }}
#     type: Opaque