# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   name: {{ .Values.service.name }}-credentials
#   annotations:
#     sealedsecrets.bitnami.com/namespace-wide: "true"
#   namespace: {{ .Release.Namespace }}
# spec:
# {{- if .Values.sealedSecret.encryptedData }}
#   encryptedData:
# {{ toYaml .Values.sealedSecret.encryptedData | indent 4 }}
# {{- end }}
#   template:
#     metadata:
#       name: {{ .Values.service.name }}-credentials
#       namespace: {{ .Release.Namespace }}
#     type: Opaque