apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}-service
spec:
  selector:
    app: {{ .Values.service.name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP